
spring:
   data:
      mongodb:
         uri: mongodb://lhq.com:27017/tiles    
   resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/offline-maps-api/
         
server:
   port: 10080
   tomcat:
      uri-encoding: UTF-8
   servlet:
      context-path: /tile-loader

config:
   maxTask: 3      #最大支持的下载任务数量
   retryNum: 3     #同一个瓦片，下载失败后最大重试次数
   tilePoolSize: 5    #后台瓦片下载线程数量，这个是java线程数，现在个人电脑配置50基本没压力
   mongoStore: 0   #是否使用mongodb存储数据，(0:本地存储，1:mongo存储)，不使用mongo存储时，从@SpringBootApplication中去掉mongo的自动化配置
   openClient: 0   #是否开启客户端，(0:不开启，1:开启)，客户端是指jxbrowser客户端
   
   baseUrl:        #瓦片下载地址
      amap: "http://wprd01.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scl=1&style=7&x={x}&y={y}&z={z}"
      bmap: "http://online3.map.bdimg.com/onlinelabel/?qt=tile&styles=pl&udt=20170712&scaler=1&p=1&x={x}&y={y}&z={z}"
      gmap: "http://mt2.google.cn/vt/lyrs=m&scale=2&hl=zh-CN&gl=cn&x={x}&y={y}&z={z}"     
   pool:           #下载器线程池
      coreSize: 2   #核心线程数
      maxSize: 6    #最大线程数
      queueSize: 2  #等待线程数
